"""Moteur alternatif basé sur FET (Free Educational Timetabling).

FET est un solveur tabu-search spécialisé pour les EDT scolaires. Sa
contrainte native `ConstraintStudentsSetMaxGapsPerDay` est ce qui le rend
particulièrement bon pour éliminer les heures creuses — point faible
observé sur OR-Tools CP-SAT.

Workflow :
 1. build_fet_xml(request) → fichier .fet (XML)
 2. exec `fet-cl` en subprocess avec timelimit
 3. parse le fichier `*_activities.xml` produit par FET
 4. mappe vers MultiGenerateResponse

Notes :
 - FET impose des contraintes de nommage : pas d'espace, caractères ASCII.
   On utilise des slugs `name_<uuid sans tirets>` puis on garde les
   mappings inverses.
 - FET exit code 0 = OK, non-zero = impossible/erreur.
"""

from __future__ import annotations

import logging
import re
import os
import shutil
import subprocess
import tempfile
import time
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Tuple

from .analysis import compute_analysis
from .schemas import (
    DayKey,
    MultiAssignmentInput,
    MultiGenerateRequest,
    MultiGenerateResponse,
    MultiPlacedEntry,
    UnplacedAssignment,
)

log = logging.getLogger(__name__)

# Mapping FET ↔ Jawal — FET utilise les noms anglais des jours
DAY_KEY_TO_FET = {
    "MON": "Monday",
    "TUE": "Tuesday",
    "WED": "Wednesday",
    "THU": "Thursday",
    "FRI": "Friday",
    "SAT": "Saturday",
    "SUN": "Sunday",
}
FET_TO_DAY_KEY = {v: k for k, v in DAY_KEY_TO_FET.items()}


def _slug(uid: str, prefix: str = "") -> str:
    """Transforme un UUID/string en identifiant FET-safe."""
    s = re.sub(r"[^A-Za-z0-9_]", "_", str(uid))
    if prefix:
        return f"{prefix}_{s}"
    return s


def _hour_name(start: str) -> str:
    """Nom d'heure FET = HH:MM directement (FET accepte les `:`)."""
    return start


def _is_teacher_available_on(teacher, day: str, slot) -> bool:
    """True si le créneau est dans une plage de dispo du prof."""
    ranges = teacher.availability.get(day, [])  # type: ignore[arg-type]
    if not ranges:
        return False
    return any(r.from_ <= slot.start_time and r.to >= slot.end_time for r in ranges)


# ─── Construction du XML FET ────────────────────────────────────────


def build_fet_xml(req: MultiGenerateRequest) -> Tuple[str, Dict[int, str], List[str]]:
    """Construit un document FET 7.x à partir de la requête.

    Retourne (xml_string, activity_id_to_assignment_id, day_order).

    Format attendu par FET 7.x : balise racine `<fet>` (minuscule), ordre
    des éléments Activity strict (Teacher, Subject, Activity_Tag, Students,
    Duration, Total_Duration, Id, Activity_Group_Id, Active, Comments).
    """
    root = ET.Element("fet", version="7.0.0")
    ET.SubElement(root, "Mode").text = "Official"
    ET.SubElement(root, "Institution_Name").text = "Jawal"
    ET.SubElement(root, "Comments").text = "Generated by Jawal solver service"

    # ─ Days ─
    days = req.days
    days_list = ET.SubElement(root, "Days_List")
    ET.SubElement(days_list, "Number_of_Days").text = str(len(days))
    for d in days:
        node = ET.SubElement(days_list, "Day")
        ET.SubElement(node, "Name").text = DAY_KEY_TO_FET[d]

    # ─ Hours ─ (slots placables uniquement ; les pauses ne sont pas des heures FET)
    placeable_slots = [s for s in req.slots if not s.is_break]
    placeable_slots_sorted = sorted(placeable_slots, key=lambda s: s.start_time)
    hours_list = ET.SubElement(root, "Hours_List")
    ET.SubElement(hours_list, "Number_of_Hours").text = str(len(placeable_slots_sorted))
    for s in placeable_slots_sorted:
        node = ET.SubElement(hours_list, "Hour")
        ET.SubElement(node, "Name").text = _hour_name(s.start_time)

    # ─ Subjects ─
    subjects_list = ET.SubElement(root, "Subjects_List")
    subjects_unique: Dict[str, str] = {}  # subject_id → slug
    for a in req.assignments:
        if a.subject_id not in subjects_unique:
            slug = _slug(a.subject_id, "s")
            subjects_unique[a.subject_id] = slug
            node = ET.SubElement(subjects_list, "Subject")
            ET.SubElement(node, "Name").text = slug
            ET.SubElement(node, "Comments").text = a.subject_label

    # Activity tags : un tag par matière. Permet de plafonner le nombre
    # d'heures/jour d'une matière par classe (MAX_SAME_SUBJECT_PER_DAY) via
    # ConstraintStudentsSetMaxHoursDailyWithAnActivityTag.
    activity_tags_list = ET.SubElement(root, "Activity_Tags_List")
    subject_tag: Dict[str, str] = {}  # subject_id → tag slug
    for sub_id, sub_slug in subjects_unique.items():
        tag_slug = f"tag_{sub_slug}"
        subject_tag[sub_id] = tag_slug
        tag_node = ET.SubElement(activity_tags_list, "Activity_Tag")
        ET.SubElement(tag_node, "Name").text = tag_slug
        ET.SubElement(tag_node, "Printable").text = "true"
        ET.SubElement(tag_node, "Comments").text = ""

    # ─ Teachers ─
    teachers_list = ET.SubElement(root, "Teachers_List")
    teacher_slugs: Dict[str, str] = {}
    for t in req.teachers:
        slug = _slug(t.id, "t")
        teacher_slugs[t.id] = slug
        node = ET.SubElement(teachers_list, "Teacher")
        ET.SubElement(node, "Name").text = slug
        ET.SubElement(node, "Comments").text = t.name

    # ─ Students Sets (Year + Group + Subgroup) ─
    #
    # 1 année "All", 1 groupe par classe, et 1 SOUS-GROUPE par demi-groupe.
    #
    # Le sous-groupe est la façon dont FET exprime le dédoublement : une
    # activité rattachée à un sous-groupe n'occupe que lui, et deux sous-groupes
    # d'une même classe peuvent donc avoir cours en même temps. Une activité
    # rattachée au groupe (la classe entière) bloque nativement tous ses
    # sous-groupes — FET gère l'imbrication.
    #
    # Sans ça, toutes les séances portaient sur la classe entière : les deux
    # moitiés d'un dédoublement devenaient deux cours à placer l'un après
    # l'autre, et FET échouait à trouver une solution.
    students_list = ET.SubElement(root, "Students_List")
    year_node = ET.SubElement(students_list, "Year")
    ET.SubElement(year_node, "Name").text = "All"
    ET.SubElement(year_node, "Number_of_Students").text = "0"
    ET.SubElement(year_node, "Comments").text = ""
    class_slugs: Dict[str, str] = {}
    group_slugs: Dict[str, str] = {}
    # Demi-groupes déclarés dans la requête, par classe.
    groups_of_class: Dict[str, list[str]] = {}
    for a in req.assignments:
        if a.group_id and a.group_id not in groups_of_class.get(a.class_id, []):
            groups_of_class.setdefault(a.class_id, []).append(a.group_id)

    for cid in req.class_ids:
        slug = _slug(cid, "c")
        class_slugs[cid] = slug
        # Trouve un nom lisible
        a_for_class = next((a for a in req.assignments if a.class_id == cid), None)
        comment = a_for_class.class_name if a_for_class else cid
        group = ET.SubElement(year_node, "Group")
        ET.SubElement(group, "Name").text = slug
        ET.SubElement(group, "Number_of_Students").text = "0"
        ET.SubElement(group, "Comments").text = comment
        for gid in groups_of_class.get(cid, []):
            gslug = _slug(gid, "g")
            group_slugs[gid] = gslug
            sub = ET.SubElement(group, "Subgroup")
            ET.SubElement(sub, "Name").text = gslug
            ET.SubElement(sub, "Number_of_Students").text = "0"
            ET.SubElement(sub, "Comments").text = f"{comment} — groupe"

    # ─ Activities ─ FET 7.x exige l'ordre strict :
    # Teacher, Subject, Activity_Tag, Students, Duration, Total_Duration,
    # Id, Activity_Group_Id, Active, Comments
    activities_list = ET.SubElement(root, "Activities_List")
    act_to_assignment: Dict[int, str] = {}
    # Ids d'activités par (classe, matière) — sert à imposer la répartition sur
    # des jours distincts (MAX_SAME_SUBJECT_PER_DAY) via ConstraintMinDaysBetweenActivities.
    acts_by_class_subject: Dict[tuple[str, str, str], list[int]] = {}
    # (classe, matière) dont la répartition « 1 par jour » est arithmétiquement
    # impossible — remontée plutôt que silencieuse.
    skipped_min_days: list[tuple[str, str, int]] = []
    # Ids d'activités par dédoublement ET par rang : la n-ième heure du Groupe 1
    # doit tomber en même temps que la n-ième heure du Groupe 2. Les apparier
    # rang par rang est ce qui rend la simultanéité exprimable — FET impose des
    # départs identiques entre activités nommées, pas entre ensembles.
    acts_by_parallel: Dict[str, list[list[int]]] = {}
    next_id = 1
    for a in req.assignments:
        teacher_slug = teacher_slugs.get(a.teacher_id)
        subj_slug = subjects_unique.get(a.subject_id)
        cls_slug = class_slugs.get(a.class_id)
        if not teacher_slug or not subj_slug or not cls_slug:
            continue
        for rank in range(a.weekly_hours):
            act_to_assignment[next_id] = a.id
            # Clé par COHORTE : la classe entière et chaque demi-groupe sont
            # comptés séparément. Les confondre imposerait des jours distincts
            # aux deux moitiés d un dédoublement, ce qui contredit la contrainte
            # qui les veut simultanées.
            acts_by_class_subject.setdefault(
                (a.class_id, a.subject_id, a.group_id or ""), []
            ).append(next_id)
            if a.parallel_key:
                slots_for_key = acts_by_parallel.setdefault(a.parallel_key, [])
                while len(slots_for_key) <= rank:
                    slots_for_key.append([])
                slots_for_key[rank].append(next_id)
            node = ET.SubElement(activities_list, "Activity")
            ET.SubElement(node, "Teacher").text = teacher_slug
            ET.SubElement(node, "Subject").text = subj_slug
            ET.SubElement(node, "Activity_Tag").text = subject_tag.get(a.subject_id, "")
            # Une séance de demi-groupe vise le sous-groupe, pas la classe.
            ET.SubElement(node, "Students").text = (
                group_slugs.get(a.group_id, cls_slug) if a.group_id else cls_slug
            )
            ET.SubElement(node, "Duration").text = "1"
            ET.SubElement(node, "Total_Duration").text = "1"
            ET.SubElement(node, "Id").text = str(next_id)
            ET.SubElement(node, "Activity_Group_Id").text = "0"
            ET.SubElement(node, "Active").text = "true"
            ET.SubElement(node, "Comments").text = ""
            next_id += 1

    ET.SubElement(root, "Buildings_List")

    # ─ Rooms ─ FET 7.x : Name, Building, Capacity, Virtual, Comments
    rooms_list = ET.SubElement(root, "Rooms_List")
    room_slugs: Dict[str, str] = {}
    for r in req.rooms:
        slug = _slug(r.id, "r")
        room_slugs[r.id] = slug
        node = ET.SubElement(rooms_list, "Room")
        ET.SubElement(node, "Name").text = slug
        ET.SubElement(node, "Building").text = ""
        ET.SubElement(node, "Capacity").text = "30"
        ET.SubElement(node, "Virtual").text = "false"
        ET.SubElement(node, "Comments").text = r.label

    # ─ Time Constraints ─
    time_constraints = ET.SubElement(root, "Time_Constraints_List")

    # Obligatoire : ConstraintBasicCompulsoryTime
    basic_t = ET.SubElement(time_constraints, "ConstraintBasicCompulsoryTime")
    ET.SubElement(basic_t, "Weight_Percentage").text = "100"
    ET.SubElement(basic_t, "Active").text = "true"
    ET.SubElement(basic_t, "Comments").text = ""

    # Phase E1 : (class_id, day, slot) interdits — par cycle
    forbidden_per_class: Dict[str, List[Tuple[str, str]]] = {}
    for f in req.forbidden_class_slots:
        # Trouve le start_time du slot
        slot = next((s for s in placeable_slots_sorted if s.id == f.slot_id), None)
        if not slot:
            continue
        forbidden_per_class.setdefault(f.class_id, []).append(
            (DAY_KEY_TO_FET[f.day], _hour_name(slot.start_time))
        )

    # Chaque classe avec des forbidden → ConstraintStudentsSetNotAvailableTimes
    for cid, not_avail in forbidden_per_class.items():
        if not not_avail or cid not in class_slugs:
            continue
        cons = ET.SubElement(time_constraints, "ConstraintStudentsSetNotAvailableTimes")
        ET.SubElement(cons, "Weight_Percentage").text = "100"
        ET.SubElement(cons, "Students").text = class_slugs[cid]
        ET.SubElement(cons, "Number_of_Not_Available_Times").text = str(len(not_avail))
        for day_name, hour_name in not_avail:
            slot_node = ET.SubElement(cons, "Not_Available_Time")
            ET.SubElement(slot_node, "Day").text = day_name
            ET.SubElement(slot_node, "Hour").text = hour_name
        ET.SubElement(cons, "Active").text = "true"
        ET.SubElement(cons, "Comments").text = ""

    # Dispos prof : ConstraintTeacherNotAvailableTimes (on liste les
    # créneaux PAS dispos)
    for t in req.teachers:
        not_available: List[Tuple[str, str]] = []  # (day_fet_name, hour_name)
        for d in days:
            for s in placeable_slots_sorted:
                if not _is_teacher_available_on(t, d, s):
                    not_available.append((DAY_KEY_TO_FET[d], _hour_name(s.start_time)))
        if not_available:
            cons = ET.SubElement(time_constraints, "ConstraintTeacherNotAvailableTimes")
            ET.SubElement(cons, "Weight_Percentage").text = "100"
            ET.SubElement(cons, "Teacher").text = teacher_slugs[t.id]
            ET.SubElement(cons, "Number_of_Not_Available_Times").text = str(len(not_available))
            for day_name, hour_name in not_available:
                slot_node = ET.SubElement(cons, "Not_Available_Time")
                ET.SubElement(slot_node, "Day").text = day_name
                ET.SubElement(slot_node, "Hour").text = hour_name
            ET.SubElement(cons, "Active").text = "true"
            ET.SubElement(cons, "Comments").text = ""

    # Contraintes paramétrables Jawal → contraintes FET équivalentes
    cons_params = req.constraints

    # NO_GAPS → ConstraintStudentsSetMaxGapsPerDay pour chaque classe
    # FET excelle ici : weight_percentage = 100 force 0 gaps quasi systématiquement.
    if cons_params.no_gaps_weight is not None and cons_params.no_gaps_weight > 0:
        # Conversion poids Jawal (1..100) → FET (50..100) pour rester réaliste
        fet_weight = max(50, min(100, 80 + cons_params.no_gaps_weight))
        for cid in req.class_ids:
            cons = ET.SubElement(time_constraints, "ConstraintStudentsSetMaxGapsPerDay")
            ET.SubElement(cons, "Weight_Percentage").text = str(fet_weight)
            ET.SubElement(cons, "Max_Gaps").text = "0"
            ET.SubElement(cons, "Students").text = class_slugs[cid]
            ET.SubElement(cons, "Active").text = "true"
            ET.SubElement(cons, "Comments").text = ""

    # Phase E2 : contraintes par classe (max/min h/jour)
    for cc in req.class_constraints:
        if cc.class_id not in class_slugs:
            continue
        cls_slug = class_slugs[cc.class_id]
        if cc.max_hours_per_day is not None:
            cons = ET.SubElement(time_constraints, "ConstraintStudentsSetMaxHoursDaily")
            ET.SubElement(cons, "Weight_Percentage").text = "100"
            ET.SubElement(cons, "Maximum_Hours_Daily").text = str(cc.max_hours_per_day)
            ET.SubElement(cons, "Students").text = cls_slug
            ET.SubElement(cons, "Active").text = "true"
            ET.SubElement(cons, "Comments").text = ""
        if cc.min_hours_per_day is not None:
            cons = ET.SubElement(time_constraints, "ConstraintStudentsSetMinHoursDaily")
            ET.SubElement(cons, "Weight_Percentage").text = "100"
            ET.SubElement(cons, "Minimum_Hours_Daily").text = str(cc.min_hours_per_day)
            ET.SubElement(cons, "Allow_Empty_Days").text = "true"
            ET.SubElement(cons, "Students").text = cls_slug
            ET.SubElement(cons, "Active").text = "true"
            ET.SubElement(cons, "Comments").text = ""

    # MAX_HOURS_PER_DAY_TEACHER → ConstraintTeacherMaxHoursDaily
    if cons_params.max_hours_per_day_teacher is not None:
        for t in req.teachers:
            cons = ET.SubElement(time_constraints, "ConstraintTeacherMaxHoursDaily")
            ET.SubElement(cons, "Weight_Percentage").text = "100"
            ET.SubElement(cons, "Teacher").text = teacher_slugs[t.id]
            ET.SubElement(cons, "Maximum_Hours_Daily").text = str(
                cons_params.max_hours_per_day_teacher
            )
            ET.SubElement(cons, "Active").text = "true"
            ET.SubElement(cons, "Comments").text = ""

    # ─ Dédoublements : les moitiés démarrent en même temps ─
    #
    # Les sous-groupes AUTORISENT le parallélisme, ils ne l'imposent pas : sans
    # cette contrainte FET plaçait les deux moitiés à des heures différentes, ce
    # qui laisse la moitié de la classe sans cours pendant que l'autre travaille.
    for ranks in acts_by_parallel.values():
        for act_ids in ranks:
            if len(act_ids) < 2:
                continue
            cons = ET.SubElement(time_constraints, "ConstraintActivitiesSameStartingTime")
            ET.SubElement(cons, "Weight_Percentage").text = "100"
            ET.SubElement(cons, "Number_of_Activities").text = str(len(act_ids))
            for aid in act_ids:
                ET.SubElement(cons, "Activity_Id").text = str(aid)
            ET.SubElement(cons, "Active").text = "true"
            ET.SubElement(cons, "Comments").text = "Dedoublement : memes horaires"

    # MAX_SAME_SUBJECT_PER_DAY.
    # NB : ConstraintStudentsSetMaxHoursDailyWithAnActivityTag est silencieusement
    # ignorée par fet-cl à l'échelle (testé : 57 violations). On utilise la
    # contrainte FET canonique et fiable : ConstraintMinDaysBetweenActivities, qui
    # impose ≥1 jour entre les séances d'une même (classe, matière) → au plus 1/jour.
    if cons_params.max_same_subject_per_day is not None:
        max_same = cons_params.max_same_subject_per_day
        if max_same <= 1:
            n_days = len(days)
            for (cid, sub_id, _gid), ids in acts_by_class_subject.items():
                if len(ids) < 2:
                    continue
                # Une matière qui revient plus souvent qu il n y a de jours ne
                # PEUT pas tenir un jour par séance. FET rejette alors le
                # fichier ENTIER avec « data is wrong », sans dire laquelle ni
                # que la cause est arithmétique. On écarte le cas plutôt que de
                # rendre tout l emploi du temps ingénérable.
                if len(ids) > n_days:
                    skipped_min_days.append((cid, sub_id, len(ids)))
                    continue
                cons = ET.SubElement(
                    time_constraints, "ConstraintMinDaysBetweenActivities"
                )
                ET.SubElement(cons, "Weight_Percentage").text = "100"
                ET.SubElement(cons, "Consecutive_If_Same_Day").text = "true"
                ET.SubElement(cons, "Number_of_Activities").text = str(len(ids))
                for aid in ids:
                    ET.SubElement(cons, "Activity_Id").text = str(aid)
                ET.SubElement(cons, "MinDays").text = "1"
                ET.SubElement(cons, "Active").text = "true"
                ET.SubElement(cons, "Comments").text = ""
        else:
            # max >= 2 : repli best-effort par tag (contrôle strict à >1 : OR-Tools).
            for cid in req.class_ids:
                if cid not in class_slugs:
                    continue
                for sub_id, tag_slug in subject_tag.items():
                    has = any(
                        a.class_id == cid and a.subject_id == sub_id
                        for a in req.assignments
                    )
                    if not has:
                        continue
                    cons = ET.SubElement(
                        time_constraints,
                        "ConstraintStudentsSetMaxHoursDailyWithAnActivityTag",
                    )
                    ET.SubElement(cons, "Weight_Percentage").text = "100"
                    ET.SubElement(cons, "Maximum_Hours_Daily").text = str(max_same)
                    ET.SubElement(cons, "Students").text = class_slugs[cid]
                    ET.SubElement(cons, "Activity_Tag").text = tag_slug
                    ET.SubElement(cons, "Active").text = "true"
                    ET.SubElement(cons, "Comments").text = ""

    # ─ Space Constraints ─
    space_constraints = ET.SubElement(root, "Space_Constraints_List")
    basic_s = ET.SubElement(space_constraints, "ConstraintBasicCompulsorySpace")
    ET.SubElement(basic_s, "Weight_Percentage").text = "100"
    ET.SubElement(basic_s, "Active").text = "true"
    ET.SubElement(basic_s, "Comments").text = ""

    # Sérialisation
    ET.indent(root)
    xml_str = '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE FET><fet>\n'
    body = ET.tostring(root, encoding="unicode")
    # FET attend la balise racine en minuscule selon les versions ; on tente
    # le format standard et fallback majuscule si nécessaire.
    full = '<?xml version="1.0" encoding="UTF-8"?>\n' + body
    if skipped_min_days:
        log.warning(
            "Repartition « 1 seance/jour » impossible pour %d couple(s) "
            "(plus de seances que de jours) : %s",
            len(skipped_min_days),
            skipped_min_days[:10],
        )

    return full, act_to_assignment, [DAY_KEY_TO_FET[d] for d in days]


# ─── Parsing de la sortie FET ──────────────────────────────────────


def parse_fet_activities(
    output_dir: Path,
    act_to_assignment: Dict[int, str],
    placeable_slots_by_start: Dict[str, str],
    days_fet_to_key: Dict[str, str],
    request: MultiGenerateRequest,
) -> List[MultiPlacedEntry]:
    """Parse le fichier `*_activities.xml` du dossier output."""
    # FET nomme : data_and_timetable/<input_basename>_activities.xml
    # mais peut varier. On cherche le premier fichier _activities.xml.
    candidates = list(output_dir.rglob("*_activities.xml"))
    if not candidates:
        return []

    placed: List[MultiPlacedEntry] = []
    assignment_meta = {a.id: a for a in request.assignments}

    for path in candidates[:1]:
        tree = ET.parse(path)
        for act in tree.findall(".//Activity"):
            aid_node = act.find("Id")
            day_node = act.find("Day")
            hour_node = act.find("Hour")
            room_node = act.find("Room")
            if aid_node is None or day_node is None or hour_node is None:
                continue
            fet_id = int(aid_node.text or "0")
            assignment_id = act_to_assignment.get(fet_id)
            if not assignment_id:
                continue
            meta = assignment_meta.get(assignment_id)
            if not meta:
                continue
            day_key = days_fet_to_key.get(day_node.text or "", None)
            slot_id = placeable_slots_by_start.get(hour_node.text or "", None)
            if not day_key or not slot_id:
                continue
            # Room : enlève le préfixe r_ pour retrouver l'UUID
            room_id = None
            if room_node is not None and room_node.text:
                raw = room_node.text
                if raw.startswith("r_"):
                    # Reconstruit l'UUID original via la liste de salles
                    candidate_id = raw[2:].replace("_", "-")
                    # Vérifie qu'elle existe dans request.rooms
                    if any(r.id == candidate_id for r in request.rooms):
                        room_id = candidate_id
                    else:
                        # Fallback : match approximatif via le slug
                        for r in request.rooms:
                            if _slug(r.id, "r") == raw:
                                room_id = r.id
                                break

            placed.append(
                MultiPlacedEntry(
                    assignment_id=assignment_id,
                    class_id=meta.class_id,
                    subject_id=meta.subject_id,
                    teacher_id=meta.teacher_id,
                    room_id=room_id,
                    day=day_key,  # type: ignore[arg-type]
                    slot_id=slot_id,
                    # Le groupe vient de l'affectation : FET place l'activité,
                    # il ne réinvente pas son public.
                    group_id=meta.group_id,
                )
            )
    return placed


# ─── Pipeline principal ────────────────────────────────────────────


def solve_with_fet(request: MultiGenerateRequest) -> MultiGenerateResponse:
    """Lance FET en subprocess et retourne le résultat normalisé."""
    started = time.time()

    if not shutil.which("fet-cl"):
        return MultiGenerateResponse(
            status="ERROR",
            solver_time_ms=0,
            placed=[],
            unplaced=[],
            message="Binaire fet-cl introuvable dans le PATH du container.",
        )

    # Préparation des index
    placeable = [s for s in request.slots if not s.is_break]
    placeable_sorted = sorted(placeable, key=lambda s: s.start_time)
    placeable_by_start: Dict[str, str] = {s.start_time: s.id for s in placeable_sorted}

    xml_str, act_to_assignment, _days_order = build_fet_xml(request)

    with tempfile.TemporaryDirectory(prefix="jawal_fet_") as tmpdir_str:
        tmpdir = Path(tmpdir_str)
        input_file = tmpdir / "jawal.fet"
        output_dir = tmpdir / "results"
        output_dir.mkdir()
        input_file.write_text(xml_str, encoding="utf-8")

        time_limit = max(10, min(int(request.max_solve_seconds), 600))

        try:
            proc = subprocess.run(
                [
                    "fet-cl",
                    f"--inputfile={input_file}",
                    f"--outputdir={output_dir}",
                    f"--timelimitseconds={time_limit}",
                    "--language=en_US",
                ],
                capture_output=True,
                text=True,
                timeout=time_limit + 30,
            )
        except subprocess.TimeoutExpired:
            return MultiGenerateResponse(
                status="ERROR",
                solver_time_ms=int((time.time() - started) * 1000),
                placed=[],
                unplaced=[],
                message=f"FET timeout après {time_limit + 30}s.",
            )

        solver_time_ms = int((time.time() - started) * 1000)

        if proc.returncode != 0:
            # fet-cl écrit ses diagnostics sur STDOUT, pas sur stderr : le
            # message ne disait donc jamais rien. On garde les deux, et on
            # conserve le XML pour pouvoir rejouer le cas.
            stderr_tail = (proc.stderr or "").strip()
            stdout_tail = (proc.stdout or "").strip()
            detail = (stderr_tail or stdout_tail or "aucun message de FET")[-800:]
            log.warning(
                "FET returncode=%s\n--- stdout ---\n%s\n--- stderr ---\n%s",
                proc.returncode,
                stdout_tail[-4000:],
                stderr_tail[-2000:],
            )
            dump_dir = os.environ.get("JAWAL_DUMP_DIR")
            if dump_dir:
                try:
                    os.makedirs(dump_dir, exist_ok=True)
                    with open(
                        os.path.join(dump_dir, "last_failed.fet"), "w", encoding="utf-8"
                    ) as fh:
                        fh.write(xml_str)
                except Exception:  # noqa: BLE001
                    pass
            return MultiGenerateResponse(
                status="INFEASIBLE",
                solver_time_ms=solver_time_ms,
                placed=[],
                unplaced=[],
                message=f"FET n'a pas trouvé de solution : {detail[:400]}",
            )

        placed = parse_fet_activities(
            output_dir,
            act_to_assignment,
            placeable_by_start,
            FET_TO_DAY_KEY,
            request,
        )

    # Calcule unplaced
    placed_hours: Dict[str, int] = {a.id: 0 for a in request.assignments}
    for p in placed:
        placed_hours[p.assignment_id] = placed_hours.get(p.assignment_id, 0) + 1

    unplaced: List[UnplacedAssignment] = []
    for a in request.assignments:
        if placed_hours.get(a.id, 0) < a.weekly_hours:
            unplaced.append(
                UnplacedAssignment(
                    assignment_id=a.id,
                    subject_label=a.subject_label,
                    teacher_id=a.teacher_id,
                    requested_hours=a.weekly_hours,
                    placed_hours=placed_hours.get(a.id, 0),
                    reason="FET n'a pas réussi à placer toutes les séances "
                    "(probable conflit de contraintes croisées).",
                )
            )

    total_req = sum(a.weekly_hours for a in request.assignments)
    total_placed = sum(placed_hours.values())
    if not unplaced:
        status = "FEASIBLE"
        msg = f"Toutes les heures placées par FET ({total_placed} h)."
    else:
        status = "PARTIAL"
        msg = f"FET : {total_placed}/{total_req} heures placées."

    analysis = compute_analysis(request, placed)

    return MultiGenerateResponse(
        status=status,  # type: ignore[arg-type]
        solver_time_ms=solver_time_ms,
        placed=placed,
        unplaced=unplaced,
        message=msg,
        consecutive_blocks=0,  # FET ne calcule pas cette métrique
        analysis=analysis,
    )
